import { Link, useParams } from 'react-router-dom';
import EmergencyMap from '../../components/map/EmergencyMap';
import SeverityBadge from '../../components/severity/SeverityBadge';
import HospitalCard from '../../components/hospital/HospitalCard';
import EmergencyTimeline from '../../components/timeline/EmergencyTimeline';
import AIDecisionCard from '../../components/transparency/AIDecisionCard';
import { useGetIncidentQuery } from '../../features/incident/incident.api';
import { useGetTimelineQuery } from '../../features/timeline/timeline.api';
import { useEscalateMutation, useResolveMutation } from '../../features/dashboard/dashboard.api';
export default function IncidentDetail() { const { incidentId } = useParams(); const { data } = useGetIncidentQuery(incidentId, { pollingInterval: 15000 }); const { data: timeline } = useGetTimelineQuery(incidentId); const [escalate] = useEscalateMutation(); const [resolve] = useResolveMutation(); const incident = data?.data; const location = incident?.location?.coordinates ? { lat: incident.location.coordinates[1], lng: incident.location.coordinates[0] } : null; return <div className="grid gap-4 lg:grid-cols-[1fr_380px]"><div className="h-[520px] overflow-hidden rounded border border-border"><EmergencyMap incidents={incident ? [incident] : []} hospitals={incident?.selectedHospital ? [incident.selectedHospital] : []} route={incident?.route} userLocation={location} /></div><aside className="space-y-3"><SeverityBadge level={incident?.severity?.level} /><p className="text-xl font-bold">{incident?.injuryType}</p>{incident?.selectedHospital && <HospitalCard item={{ hospital: incident.selectedHospital, etaSeconds: incident.route?.etaSeconds, reasoning: incident.severity?.reasoning }} selected />}<AIDecisionCard reasoning={incident?.severity?.reasoning} /><div className="grid grid-cols-3 gap-2"><button onClick={() => escalate({ id: incidentId, reason: 'Responder escalation' })} className="rounded bg-orange-700 py-2">Escalate</button><Link to={'/responder/navigation/' + incidentId} className="rounded bg-blue-700 py-2 text-center">Navigate</Link><button onClick={() => resolve({ id: incidentId, outcome: 'handoff complete' })} className="rounded bg-green-700 py-2">Resolve</button></div><EmergencyTimeline events={timeline?.data || []} /></aside></div>; }
