import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { useSelector } from 'react-redux';
import EmergencyMap from '../../components/map/EmergencyMap';
import SeverityBadge from '../../components/severity/SeverityBadge';
import SeverityGauge from '../../components/severity/SeverityGauge';
import ETAChip from '../../components/hospital/ETAChip';
import HospitalCard from '../../components/hospital/HospitalCard';
import FirstAidChat from '../../components/firstaid/FirstAidChat';
import EmergencyTimeline from '../../components/timeline/EmergencyTimeline';
import useSocket from '../../hooks/useSocket';
import { useGetIncidentQuery } from '../../features/incident/incident.api';
import { useGetTimelineQuery } from '../../features/timeline/timeline.api';
export default function ActiveEmergency() { const { incidentId } = useParams(); const active = useSelector((state) => state.sos.activeSOS); const id = incidentId || active?._id; const { data } = useGetIncidentQuery(id, { skip: !id, pollingInterval: 30000 }); const { data: timelineData } = useGetTimelineQuery(id, { skip: !id }); const [tab, setTab] = useState('Status'); const [incident, setIncident] = useState(null); const [events, setEvents] = useState([]); const [responderLocation, setResponderLocation] = useState(null); const { socket } = useSocket('/emergency', id); useEffect(() => { if (data?.data) setIncident(data.data); }, [data]); useEffect(() => { if (timelineData?.data) setEvents(timelineData.data); }, [timelineData]); useEffect(() => { if (!socket) return undefined; socket.on('sos:updated', setIncident); socket.on('timeline:update', (event) => setEvents((items) => [...items, event])); socket.on('responder:location', setResponderLocation); socket.on('eta:update', (eta) => setIncident((item) => item ? { ...item, route: { ...item.route, ...eta } } : item)); return () => { socket.off('sos:updated'); socket.off('timeline:update'); socket.off('responder:location'); socket.off('eta:update'); }; }, [socket]); const location = incident?.location?.coordinates ? { lat: incident.location.coordinates[1], lng: incident.location.coordinates[0] } : null; return <div className="mx-auto grid h-[calc(100vh-100px)] max-w-[430px] grid-rows-[60%_40%] overflow-hidden rounded border border-border md:max-w-none"><EmergencyMap incidents={incident ? [incident] : []} hospitals={incident?.selectedHospital ? [incident.selectedHospital] : []} route={incident?.route} userLocation={location} responderLocation={responderLocation} /><section className="overflow-auto bg-dark p-3"><div className="mb-3 grid grid-cols-4 gap-1">{['Status', 'Hospital', 'First Aid', 'Timeline'].map((item) => <button key={item} onClick={() => setTab(item)} className={(tab === item ? 'bg-red-600' : 'bg-surface') + ' rounded px-2 py-2 text-xs'}>{item}</button>)}</div>{tab === 'Status' && <div className="space-y-3"><SeverityBadge level={incident?.severity?.level} /><SeverityGauge score={incident?.severity?.score || 0} level={incident?.severity?.level || 'LOW'} /><ETAChip seconds={incident?.route?.etaSeconds || 0} /><p className="text-sm text-slate-300">Responder: {incident?.responder?.name || 'Assigning now'}</p></div>}{tab === 'Hospital' && incident?.selectedHospital && <HospitalCard item={{ hospital: incident.selectedHospital, etaSeconds: incident.route?.etaSeconds, score: 0, reasoning: incident.severity?.reasoning }} selected />}{tab === 'First Aid' && <FirstAidChat messages={[]} steps={[]} onSend={() => {}} />}{tab === 'Timeline' && <EmergencyTimeline events={events} />}</section></div>; }
